10. Código/SistemaDelivery/SistemaDelivery/Controllers/AdministradorController.cs
using System.Linq;
using System.Collections.Generic;
using System.Web.Mvc;
using Model.Models;
using Negocio.Business;
using SistemaDelivery.Util;
using Model.Models.Exceptions;
using System;

namespace SistemaDelivery.Controllers
{
    [Authenticated]
    [CustomAuthorize(NivelAcesso = Util.TipoUsuario.ADMINISTRADOR)]
    public class AdministradorController : Controller
    {

        private GerenciadorPessoa gerenciador;

        public AdministradorController()
        {
            gerenciador = new GerenciadorPessoa();
        }
       
        public ActionResult Index()
        {
            try
            {
                return View();
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar acessar ação.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar acessar ação", e);
            }
        }
        
        public ActionResult Details(int? id)
        {
            try
            {
                if (id.HasValue)
                {
                    Usuario usuario = gerenciador.ObterUsuario(id);
                    if (usuario != null)
                        return View(usuario);
                }
                return RedirectToAction("ListagemUsuarios");
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", e);
            }
        }
        
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar acessar ação.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar acessar ação", e);
            }
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Pessoa pessoa = gerenciador.ObterByLogin(collection["Login"]);
                    if (pessoa == null)
                    {
                        collection["Senha"] = Criptografia.GerarHashSenha(collection["Login"] + collection["Senha"]);
                        Usuario usuario = new Usuario();
                        TryUpdateModel<Usuario>(usuario, collection.ToValueProvider());
                        usuario.ConfirmarSenha = usuario.Senha;
                        gerenciador.Adicionar(usuario);
                        return RedirectToAction("ListagemUsuarios");
                    }
                    ModelState.AddModelError("", "Login já existente.");
                }
                return View();
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar criar o objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar criar o objeto.", e);
            }
        }
        
        public ActionResult AlterarDados()
        {
            try
            {
                Usuario administrador = (Usuario)SessionHelper.Get(SessionKeys.Pessoa);
                if (administrador != null)
                    return View(administrador);
                return RedirectToAction("Index");
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", e);
            }
        }


        [HttpPost]
        public ActionResult AlterarDados(FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Usuario administrador = new Usuario();
                    TryUpdateModel<Usuario>(administrador, collection.ToValueProvider());
                    SessionHelper.Set(SessionKeys.Pessoa, administrador);
                    gerenciador.Editar(administrador);
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar alterar as informações do objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar alterar as informações do objeto.", e);
            }
        }
        
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id.HasValue)
                {
                    Usuario usuario = gerenciador.ObterUsuario(id);
                    if (usuario != null)
                        return View(usuario);
                }
                return RedirectToAction("ListagemUsuarios");
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", e);
            }
        }

        [HttpPost]
        public ActionResult Edit(FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Usuario usuario = new Usuario();
                    TryUpdateModel<Usuario>(usuario, collection.ToValueProvider());
                    gerenciador.Editar(usuario);
                    return RedirectToAction("ListagemUsuarios");
                }
                return View();
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar alterar as informações do objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar alterar as informações do objeto.", e);
            }
        }
        
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id.HasValue)
                {
                    Usuario usuario = gerenciador.ObterUsuario(id);
                    if (usuario != null)
                        return View(usuario);
                }
                return RedirectToAction("ListagemUsuarios");
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", e);
            }
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    gerenciador.Remover(new Usuario { Id = id });
                    return RedirectToAction("ListagemUsuarios");
                }
                return View();
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar remover o objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar remover o objeto.", e);
            }
        }
        
        public ActionResult ListagemUsuarios()
        {
            try
            {
                List<Usuario> usuarios = gerenciador.ObterUsuarios().Where(u => u.Id != ((Usuario)SessionHelper.Get(SessionKeys.Pessoa)).Id).ToList();
                if (usuarios == null || usuarios.Count == 0)
                    usuarios = null;
                return View(usuarios);
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar obter os objetos.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar obter os objetos.", e);
            }
        }
        
        public ActionResult AlterarSenha()
        {
            try
            {
                return View();
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar acessar ação.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar acessar ação", e);
            }
        }

        [HttpPost]
        public ActionResult AlterarSenha(FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Usuario administrador = (Usuario)SessionHelper.Get(SessionKeys.Pessoa);
                    String senha = Criptografia.GerarHashSenha(administrador.Login + collection["SenhaAtual"]);

                    if (senha.ToLowerInvariant().Equals(administrador.Senha.ToLowerInvariant()))
                    {
                        administrador.Senha = Criptografia.GerarHashSenha(administrador.Login + collection["NovaSenha"]);
                        administrador.ConfirmarSenha = administrador.Senha;
                        SessionHelper.Set(SessionKeys.Pessoa, administrador);
                        gerenciador.Editar(administrador);
                        return RedirectToAction("Index");
                    }

10. Código/SistemaDelivery/SistemaDelivery/Controllers/ProdutoController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Model.Models;
using Negocio.Business;
using SistemaDelivery.Util;
using Model.Models.Exceptions;
using System;

namespace SistemaDelivery.Controllers
{
    [Authenticated]
    [CustomAuthorize(NivelAcesso = Util.TipoUsuario.EMPRESA)]
    public class ProdutoController : Controller
    {
        private GerenciadorProduto gerenciador;

        public ProdutoController()
        {
            gerenciador = new GerenciadorProduto();
        }

        public ActionResult Index()
        {
            try
            {
                Empresa empresa = (Empresa)SessionHelper.Get(SessionKeys.Pessoa);
                List<Produto> produtos = gerenciador.ObterTodos(empresa.Id);
                if (produtos == null || produtos.Count == 0)
                    produtos = null;
                return View(produtos);
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar obter os objetos.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar obter os objetos.", e);
            }
        }

        public ActionResult Details(int? id)
        {
            try
            {
                if (id.HasValue)
                {
                    Produto produto = gerenciador.Obter(id);
                    if (produto != null)
                        return View(produto);
                }
                return RedirectToAction("Index");
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", e);
            }
        }

        public ActionResult Create()
        {
            try
            {
                ViewBag.ListaDescricao = new SelectList(gerenciador.ObterTodosTipos(), "Id", "Descricao");
                ViewBag.ListaMarca = new SelectList(gerenciador.ObterTodosTipos(), "Id", "Marca");
                return View();
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar obter as informações para criação do objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar obter as informações para criação do objeto.", e);
            }
        }

        [HttpPost]
        public ActionResult Create(FormCollection form)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Empresa empresa = (Empresa)SessionHelper.Get(SessionKeys.Pessoa);
                    if (empresa != null)
                    {
                        Produto produto = new Produto() { TipoProduto = new TipoProduto(), Empresa = new Empresa() };
                        TryUpdateModel<Produto>(produto, form.ToValueProvider());
                        produto.Empresa = empresa;
                        produto.TipoProduto = gerenciador.ObterTipoProduto(produto.TipoProduto.Id);
                        gerenciador.Adicionar(produto);
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar criar o objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar criar o objeto.", e);
            }
        }

        public ActionResult Edit(int? id)
        {
            try
            {
                if (id.HasValue)
                {
                    Produto produto = gerenciador.Obter(id);
                    if (produto != null)
                        return View(produto);
                }
                return RedirectToAction("Index");
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", e);
            }            
        }

        [HttpPost]
        public ActionResult Edit(FormCollection form)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Produto produto = new Produto() { Empresa = new Empresa(), TipoProduto = new TipoProduto() };
                    TryUpdateModel<Produto>(produto, form.ToValueProvider());
                    produto.Empresa = (Empresa)SessionHelper.Get(SessionKeys.Pessoa);
                    produto.TipoProduto = gerenciador.ObterTipoProduto(produto.TipoProduto.Id);
                    gerenciador.Editar(produto);
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar alterar as informações do objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar alterar as informações do objeto.", e);
            }
        }

        public ActionResult Delete(int? id)
        {
            try
            {
                if (id.HasValue)
                {
                    Produto produto = gerenciador.Obter(id);
                    if (produto != null)
                        return View(produto);
                }
                return RedirectToAction("Index");
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar obter as informações do objeto.", e);
            }

        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    gerenciador.Remover(new Produto { Id= id});
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (NegocioException n)
            {
                throw new ControllerException("Erro ao tentar remover o objeto.", n);
            }
            catch (Exception e)
            {
                throw new ControllerException("Erro ao tentar remover o objeto.", e);
            }
        }
    }
}

10. Código/SistemaDelivery/SistemaDelivery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -DeliveryAgua&Gas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div style=" font-family:'Times New Roman'; color:#FFFFFF; background-color: darkslateblue" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></button>
                @Html.ActionLink("DELIVERYÁGUA&GÁS", "Index", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (SistemaDelivery.Util.SessionHelper.Get(SistemaDelivery.Util.SessionKeys.Pessoa) == null)
                {
                    <li>@Html.ActionLink(" ACESSAR", "Login", "Home")</li>
                }
                else
                {
                    <li>@Html.ActionLink(" MEUS PEDIDOS ", "ListagemPedidos", "Pedido")</li>

                    String controlle = "";
                    Model.Models.Pessoa pessoa = SistemaDelivery.Util.SessionHelper.Get(SistemaDelivery.Util.SessionKeys.Pessoa) as Model.Models.Pessoa;
                    if (typeof(Model.Models.Empresa) == pessoa.GetType())
                    {
                     <!--EMPRESA-->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    PRODUTOS
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <p class="dropdown-item">@Html.ActionLink("CADASTRADOS", "Index", "Produto")</p>
                                    <p class="dropdown-item">@Html.ActionLink("CADASTRAR NOVO", "Create", "Produto")</p>
                                </div>
                            </li>
                        controlle = "Empresa";
                    }
                    else
                    {
                        if (typeof(Model.Models.Usuario) == pessoa.GetType() && ((Model.Models.Usuario)pessoa).IsAdmin)
                        {
                             <!--ADMINISTRADOR -->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    DISTRIBUIDORAS
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <p class="dropdown-item">@Html.ActionLink("CADASTRADAS", "ListagemDistribuidoras", "Empresa")</p>
                                    <p class="dropdown-item">@Html.ActionLink("CADASTRAR NOVA", "Create", "Empresa")</p>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    USUARIOS
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <p class="dropdown-item">@Html.ActionLink("CADASTRADOS", "ListagemUsuarios", "Administrador")</p>
                                    <p class="dropdown-item">@Html.ActionLink("CADASTRAR NOVO", "Create", "Administrador")</p>
                                </div>
                            </li>
                            controlle = "Administrador";
                        }
                        else
                        {
                            if ((typeof(Model.Models.Usuario) == pessoa.GetType() && !((Model.Models.Usuario)pessoa).IsAdmin))
                            {
                                <li>@Html.ActionLink(" DISTRIBUIDORAS ", "ListagemDistribuidoras", "Empresa")</li>
                                controlle = "Cliente";
                            }
                        }

                    }
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            MEU PERFIL
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <p class="dropdown-item">@Html.ActionLink("ALTERAR SENHA", "AlterarSenha", controlle)</p>
                            <p class="dropdown-item">@Html.ActionLink("ALTERAR DADOS", "AlterarDados", controlle)</p>
                        </div>
                    </li>
                    <li>@Html.ActionLink(" SAIR ", "Logout", "Home")</li>
                }
            </ul>
        </div>
      </div>
    </div>
    <hr />
    @RenderBody()
    <hr />
    <div class="panel-footer">
        <p>&copy; @DateTime.Now.Year -Delivery Água e Gás trazendo o produto para pertinho de VOCÊ!</p>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>